### ISSUE TITLE
Revizije su prevelike

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-067-whiteman#4]
Ne možete da promenite dosadašnje revizije, ali za naredne - napravite da je svaka revizija mala logička celina, ne da bude ogroman code-dump kao https://github.com/MATF-RG16/RG16-067-whiteman/commit/66430a76ba036e969701a487c44994fbea47935a

**Comment by Stivisa** [comment]
Slazem se naravno , greska ...
